"""empty message

Revision ID: 04e6b84ff6f6
Revises: 53d9bd0507f1
Create Date: 2017-10-02 22:38:22.643683

"""

# revision identifiers, used by Alembic.
revision = '04e6b84ff6f6'
down_revision = '53d9bd0507f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
